[package]
name = "sputnik"
version = "0.1.0"
authors = ["juripetersen <juri@hey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
requests = "*"
scraper = "*"
async-std = "*"
async-recursion = "*"
